singleQuote: true
trailingComma: "es5"
printWidth: 120
commaDangle:
  - 2
  - functions: ignore
    objects: always-multiline
    arrays: always-multiline
    imports: always-multiline
    exports: always-multiline
